### ISSUE TITLE
ModuleNotFoundError: No module named '_watchdog_fsevents' 

### ISSUE THREAD

**Issue by dhnam** [gorakhargosh/watchdog#1008]
```python
from watchdog.observers.fsevents import FSEventsObserver
```

gives me
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/vscode/.local/lib/python3.11/site-packages/watchdog/observers/fsevents.py", line 32, in <module>
    import _watchdog_fsevents as _fsevents  # type: ignore[import]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_watchdog_fsevents'
```

**Comment by altendky** [comment]
Based on your path (`/home/...`) it looks like you are running Linux.  Is that correct?  `FSEvents` is a macOS only thing I believe.

https://github.com/gorakhargosh/watchdog/blob/75a3289dd3215124149d82eb27b8a75899b06a8f/src/watchdog/observers/fsevents.py#L21

What is the bigger picture here that lead you to run into this error?

Regardless, it could certainly be useful to provide a better message here to help out developers.

**Comment by dhnam** [comment]
Yup it's on Linux - actually it's on codespace. It is used on other library (pyedifice) so I installed watchdog, and ran into this error.

Current version of pyedifice doesn't handle this exception well (It actually checks exception, but expects wrong exception.) so I ran into the problem.

Guess it's more like problem of said library.

**Comment by altendky** [comment]
At present, I think it is likely that your issue will be addressed by a change in the other library.  But, let's leave this issue open as there is room for improvement around the handling of this in watchdog itself.
