### ISSUE TITLE
Version 1.0.2 is not available in PyPi

### ISSUE THREAD

**Issue by Ant1ng2** [gorakhargosh/watchdog#1024]
Hi all,

Just recently, I attempted creation of a Lyftvenv in https://github.com/lyft/bookkeeper, but I wasn't able to fully build because of this issue
```
*******************************************************************************
ERROR: Could not find a version that satisfies the requirement watchdog==1.0.2 (from versions: 0.8.3, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 1.0.0, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 3.0.0)
ERROR: No matching distribution found for watchdog==1.0.2
*******************************************************************************
===============================================================================
Unexpected error!
===============================================================================

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/lyftvenv/1.6.1/libexec/lib/python3.8/site-packages/lyftvenv/lyftvenv.py", line 1708, in bug_report
    yield
  File "/opt/homebrew/Cellar/lyftvenv/1.6.1/libexec/lib/python3.8/site-packages/lyftvenv/lyftvenv.py", line 1858, in execute
    exit_code, action_taken = cmd_venv(
  File "/opt/homebrew/Cellar/lyftvenv/1.6.1/libexec/lib/python3.8/site-packages/lyftvenv/lyftvenv.py", line 1335, in cmd_venv
    _install_venv(
  File "/opt/homebrew/Cellar/lyftvenv/1.6.1/libexec/lib/python3.8/site-packages/lyftvenv/lyftvenv.py", line 1164, in _install_venv
    _run_slow_command(
  File "/opt/homebrew/Cellar/lyftvenv/1.6.1/libexec/lib/python3.8/site-packages/lyftvenv/lyftvenv.py", line 700, in _run_slow_command
    raise AssertionError(
AssertionError: ('/Users/aling/.cache/lyftvenv/v/bookkeeper/h961hnY2VwVTPasJSiBfOkf9idc/bin/pip', 'install', '--only-binary', 'cryptography', '--only-binary', 'grpcio', '--only-binary', 'pandas', '--find-links=file:///opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/wheels', '--no-compile', '-r', '/Users/aling/src/bookkeeper/requirements.txt') returned 1, output is printed above (if building a new venv, try `lyftvenv venv -v` to see full output)

*******************************************************************************
Version info:
!!! lyftvenv version
1.6.1
!!! platform
macos_14
!!! python bundle version
0.0.0
!!! installed python bundle version
0.0.0
*******************************************************************************
```

This indicates to me that the 1.0.2 version has been removed or is inaccessible in PyPi recently, as I was able to create a Lyftvenv weeks ago with the same dependency. My ask is if it is possible to get this restored or another alternative version we should be using?

Thanks!

**Comment by Ant1ng2** [comment]
Figured out the issue, there is no Python wheel that supports Python 3.10 and MacOS. Refactoror automatically updated our repository to Python 3.10.

**Comment by BoboTiG** [comment]
1.0.2 is quite old, and should be used for those wanting support for Python 2.7. It's no more maintained. Could you use the latest version (3.0.0 at the time)?
