### ISSUE TITLE
KeyError: 731

### ISSUE THREAD

**Issue by SeyZ** [gorakhargosh/watchdog#117]
First of all, thanks for this awesome project. It's really useful.

When I use watchdog intensively, I have sometime this kind of exception:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/seyz/workspace/virtenvs/foo/lib/python2.7/site-packages/watchdog/observers/api.py", line 191, in run
    self.queue_events(self.timeout)
  File "/home/seyz/workspace/virtenvs/foo/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 748, in queue_events
    inotify_events = self._inotify.read_events()
  File "/home/seyz/workspace/virtenvs/foo/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 538, in read_events
    wd_path = self._path_for_wd[wd]
KeyError: 731
```

Edit issue:

Here's exactly the same stacktrace (with the error at the same line) but the KeyError is now 730. Could you help me ?

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/seyz/workspace/virtenvs/foo/lib/python2.7/site-packages/watchdog/observers/api.py", line 191, in run
    self.queue_events(self.timeout)
  File "/home/seyz/workspace/virtenvs/foo/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 748, in queue_events
    inotify_events = self._inotify.read_events()
  File "/home/seyz/workspace/virtenvs/foo/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 538, in read_events
    wd_path = self._path_for_wd[wd]
KeyError: 730
```

**Comment by danilobellini** [comment]
That's not fixed yet, and it isn't so random as it perhaps seems. I'm having this issue "consistently" here. I mean, all the time (on every run), unless I add an artificial 50ms sleep to the event handler:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/watchdog/observers/inotify_buffer.py", line 59, in run
    inotify_events = self._inotify.read_events()
  File "/usr/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 307, in read_events
    wd_path = self._path_for_wd[wd]
KeyError: 966
```

**Comment by danilobellini** [comment]
I was checking here the cause, as it seems it's due to a path that appears twice in the `self._path_for_wd`. In the execution order, `Inotify.read_events` calls `_remove_watch_bookkeeping` to remove the wd=964, but it removes the wd=966 that seem to have the same source path:

```
for loop: wd=964, name=
caller (when inotify_event.is_ignored): wd=964, src_path=./.tox/log
_remove_watch_bookkeeping: wd=966, del _path_for_wd=./.tox/log
for loop: wd=966, name=tox-0.log
[... crashes ...]
```

Should I open a new issue?
