### ISSUE TITLE
watchdog basic example doesn't work when you pass in a filename

### ISSUE THREAD

**Issue by mgrandi** [gorakhargosh/watchdog#296]
Using the basic script that is on the watchdog github / pypi page on windows doesn't work when you pass in an exact filename , to watch a specific file

watchdog version: (from pypi) - Version: 0.8.3

windows version: 'Windows-8-6.2.9200'

output: 

```
C:\Users\Mark Grandi>py -3 watchdogtest.py tmp.txt
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Users\Mark Grandi\AppData\Roaming\Python\Python34\site-packages\watchdog\observers\api.py", line 146, in run
    self.queue_events(self.timeout)
  File "C:\Users\Mark Grandi\AppData\Roaming\Python\Python34\site-packages\watchdog\observers\read_directory_changes.py", line 77,
in queue_events
    winapi_events = read_events(self._handle, self.watch.is_recursive)
  File "C:\Users\Mark Grandi\AppData\Roaming\Python\Python34\site-packages\watchdog\observers\winapi.py", line 347, in read_events
    buf, nbytes = read_directory_changes(handle, recursive)
  File "C:\Users\Mark Grandi\AppData\Roaming\Python\Python34\site-packages\watchdog\observers\winapi.py", line 307, in read_directory_changes
    raise e
  File "C:\Users\Mark Grandi\AppData\Roaming\Python\Python34\site-packages\watchdog\observers\winapi.py", line 303, in read_directory_changes
    ctypes.byref(nbytes), None, None)
  File "C:\Users\Mark Grandi\AppData\Roaming\Python\Python34\site-packages\watchdog\observers\winapi.py", line 108, in _errcheck_bool
    raise ctypes.WinError()
OSError: [WinError 87] The parameter is incorrect.
```

**Comment by mfitzp** [comment]
Have the same error here (using Python Python 3.4.1; watchdog 0.8.3):

  File "C:\Python34\lib\site-packages\watchdog\observers\winapi.py", line 108, i
n _errcheck_bool
    raise ctypes.WinError()
OSError: [WinError 87] The parameter is incorrect.

**Comment by FraPochetti** [comment]
I am facing the same issue. Has anyone been able to figure this out?

**Comment by BoboTiG** [comment]
What code are you talking about exactly?

**Comment by michael-angelozzi** [comment]
I have the same issue. When one is trying to watch a file, instead of a dir for changes. For example, when you are scheduling an observer, you get an error if you pass in a file path (instead of a dir path):

    from watchdog.observers import Observer
    # This works
    dir_ = "C:\code\"
    observer.schedule(TaskHandler(self), dir_, recursive=False)

    # This generate an error
    file = r"C:\code\test.txt"
    observer.schedule(TaskHandler(self), file, recursive=False)

The error generated:

      File "C:\Users\Michael\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
        self.run()
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\api.py", line 146, in run
        self.queue_events(self.timeout)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 75, in queue_events
        winapi_events = read_events(self._handle, self.watch.is_recursive)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 346, in read_events
        buf, nbytes = read_directory_changes(handle, recursive)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 306, in read_directory_changes
        raise e
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 302, in read_directory_changes
        ctypes.byref(nbytes), None, None)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 107, in _errcheck_bool
        raise ctypes.WinError()
    OSError: [WinError 87] The parameter is incorrect.
    Exception in thread Thread-8:
    Traceback (most recent call last):
      File "C:\Users\Michael\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
        self.run()
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\api.py", line 146, in run
        self.queue_events(self.timeout)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 75, in queue_events
        winapi_events = read_events(self._handle, self.watch.is_recursive)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 346, in read_events
        buf, nbytes = read_directory_changes(handle, recursive)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 306, in read_directory_changes
        raise e
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 302, in read_directory_changes
        ctypes.byref(nbytes), None, None)
      File "C:\code\linkcube\venv\lib\site-packages\watchdog\observers\winapi.py", line 107, in _errcheck_bool
        raise ctypes.WinError()
    OSError: [WinError 87] The parameter is incorrect.
