### ISSUE TITLE
failed to watch /tmp on ubuntu 15.04

### ISSUE THREAD

**Issue by liangqi** [gorakhargosh/watchdog#321]
I just used the "A Simple Example" in "Quickstart", and add "/tmp" as parameter. 

Permission of /tmp is:

```
drwxrwxrwt  10 root root  4096 juni  10 10:40 tmp
```

But got following error:

```
Traceback (most recent call last):
  File "./new2.py", line 22, in <module>
    observer.start()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/utils/__init__.py", line 111, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_c.py", line 187, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_c.py", line 371, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_c.py", line 385, in _add_watch
    Inotify._raise_error()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_c.py", line 406, in _raise_error
    raise OSError(os.strerror(err))
OSError: Permission denied
```

Thanks for help.

**Comment by BoboTiG** [comment]
This is normal as ou do not have rights on that folder. What do you want watchdog to do? You should just check that you have access to that folder before trying the watch changes.
