### ISSUE TITLE
Watchdog doesn't work along with eventlet

### ISSUE THREAD

**Issue by gnuton** [gorakhargosh/watchdog#332]
Hi!
Observer cannot be instantiated in case  eventlet.monkey_patch() patches Thread.

Here is the code which shows the problem:
```python
# !/usr/bin/env python

from watchdog.observers import Observer
import eventlet
eventlet.monkey_patch()
obs = Observer() # THIS FAILS because of monkey_patch patches threads
```

Here is the exception I get running the above code
```shell
/usr/bin/python2.7 /home/gnuton/GIT/flickrsmartsync/flickrsmartsync/flickrsmartsync/test.py
Traceback (most recent call last):
  File "/home/gnuton/GIT/flickrsmartsync/flickrsmartsync/flickrsmartsync/test.py", line 6, in <module>
    obs = Observer() # THIS FAILS because of monkey_patch patches threads
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify.py", line 186, in **init**
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 208, in **init**
    EventDispatcher.**init**(self, timeout)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 164, in **init**
    self._event_queue = EventQueue()
  File "/usr/lib/python2.7/Queue.py", line 28, in __init__
    self._init(maxsize)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/utils/bricks.py", line 87, in _init
    queue.Queue._init(self, maxsize)
TypeError: unbound method _init() must be called with Queue instance as first argument (got EventQueue instance instead)
```

**Comment by gnuton** [comment]
Just out of curiosity this morning I tried to get watchdog observer working along with gevent lib.
Monkey patching thread doesn't make any trouble to the Observer constructor, but it doesn't work as it should.. or at least the tests of my app I don't pass.

**Comment by tacy** [comment]
+1

I want to call a method with eventlet in Myhandler. I just fix it use multiprocess

**Comment by samy100** [comment]
+1

**Comment by e0ne** [comment]
+1

**Comment by tohyongcheng** [comment]
+1

**Comment by audrummer15** [comment]
+1

**Comment by Catelemmon** [comment]
+1

**Comment by BoboTiG** [comment]
Fixed in master :)
