### ISSUE TITLE
Inotify._parse_event_buffer 'NoneType' object has no attribute '_parse_event_buffer'

### ISSUE THREAD

**Issue by tjerkw** [gorakhargosh/watchdog#333]
On this line in inotify_c.py: (watchdog==0.8.3)

```
for wd, mask, cookie, name in Inotify._parse_event_buffer(event_buffer):
```

I'm getting the following exception:

```
11:52:50 web.1   | Traceback (most recent call last):
11:52:50 web.1   |   File "/var/lib/python-2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
11:52:50 web.1   |   File "/home/vagrant/envs/tiqetsapi/lib/python2.7/site-packages/watchdog/observers/inotify_buffer.py", line 59, in run
11:52:50 web.1   |   File "/home/vagrant/envs/tiqetsapi/lib/python2.7/site-packages/watchdog/observers/inotify_c.py", line 304, in read_events
11:52:50 web.1   | <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute '_parse_event_buffer'
11:52:50 web.1   | [2015-09-11 11:52:50,813] p1850 {_internal:87} INFO -  * Restarting with inotify reloader
```

**Comment by BoboTiG** [comment]
Closing as it lacks of information. A reproduction case would be necessary. Please re-open if needed.
