### ISSUE TITLE
WinError 58 makes the watchdog to fail the upcoming requests

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [gorakhargosh/watchdog#334]
Hi all,

When monitoring a folder inside a QNAP, I can get events for newly created files. However, if the new file is a directory, the watchdog crashes with a system error.

I suspect it is because the file is still being copied, but that should not be a reason to crash the listener.

Application is running on Windows 8.1 Pro.
Stack Trace:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\watchdog-0.8.3-py3.4.egg\watchdog\observers\api.py", line 146, in run
    self.queue_events(self.timeout)
  File "C:\Python34\lib\site-packages\watchdog-0.8.3-py3.4.egg\watchdog\observers\read_directory_changes.py", line 77, in queue_events
    winapi_events = read_events(self._handle, self.watch.is_recursive)
  File "C:\Python34\lib\site-packages\watchdog-0.8.3-py3.4.egg\watchdog\observers\winapi.py", line 347, in read_events
    buf, nbytes = read_directory_changes(handle, recursive)
  File "C:\Python34\lib\site-packages\watchdog-0.8.3-py3.4.egg\watchdog\observers\winapi.py", line 307, in read_directory_changes
    raise e
  File "C:\Python34\lib\site-packages\watchdog-0.8.3-py3.4.egg\watchdog\observers\winapi.py", line 303, in read_directory_changes
    ctypes.byref(nbytes), None, None)
  File "C:\Python34\lib\site-packages\watchdog-0.8.3-py3.4.egg\watchdog\observers\winapi.py", line 108, in _errcheck_bool
    raise ctypes.WinError()
OSError: [WinError 58] The specified server cannot perform the requested operation.
```

**Comment by michaelPf85** [comment]
Same problem around here, with a WinError 64 and the message : The specified network name is no longer available. This happens when folder is served from a file server that becomes unavailable (SMB share).

How could we catch these kind of error, to retry attaching an observer later ?

**Comment by mikkelcp1** [comment]
I am also now looking for a solution to delay/retry dirwatcher thread on:
OSError: [WinError 64] The specified network name is no longer available

**Comment by BoboTiG** [comment]
What solution (code changes) would you like to see in watchdog?
