### ISSUE TITLE
setup.py test fails

### ISSUE THREAD

**Issue by anntzer** [gorakhargosh/watchdog#338]
Both with PyPI tarball and current HEAD:
```
$ python setup.py test                                                                                                                                                [15-11-10 14:18:43]
running test
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    zip_safe=False
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 73, in finalize_options
    'tests']
AttributeError: can't set attribute
```
(running py.test directly works fine.)

**Comment by carlcarl** [comment]
Seems solved? I don't have this issue.

**Comment by anntzer** [comment]
yup.
