### ISSUE TITLE
KeyErrorL 'self' when --trace used with log subcommand

### ISSUE THREAD

**Issue by jonblack** [gorakhargosh/watchdog#381]
Running `watchmedo log --trace .` results in the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/watchmedo", line 9, in <module>
    load_entry_point('watchdog==0.8.3', 'console_scripts', 'watchmedo')()
  File "/usr/local/lib/python3.5/site-packages/watchdog/watchmedo.py", line 566, in main
    parser.dispatch()
  File "/usr/local/lib/python3.5/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/local/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/local/lib/python3.5/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/usr/local/lib/python3.5/site-packages/watchdog/watchmedo.py", line 334, in log
    ignore_directories=args.ignore_directories)
  File "/usr/local/lib/python3.5/site-packages/watchdog/utils/echo.py", line 98, in wrapped
    for a in argnames[len(v):] if a not in k]
  File "/usr/local/lib/python3.5/site-packages/watchdog/utils/echo.py", line 98, in <listcomp>
    for a in argnames[len(v):] if a not in k]
KeyError: 'self'
```

**Comment by DonyorM** [comment]
Sorry it took us so long to respond to this. I'm working on a fix now.

I've traced the issue down to a difference between python 2 and 3, in line 98 of the echo.py file, there's a call `len(v)`. In python2 this comes out as 1, in python 3 it returns 0. That's the issue, I need to figure out what's causing the difference and how to fix it.

**Comment by DonyorM** [comment]
Fixed with commit  d33bee0.

**Comment by Lucas-C** [comment]
Could you please include this fix in a release ?

**Comment by DonyorM** [comment]
@gorakhargosh is it possible to have a new release of watchdog?
