### ISSUE TITLE
KeyError: -1  for  self._inotify.read_events()

### ISSUE THREAD

**Issue by ftao** [gorakhargosh/watchdog#382]
I'm monitor one directory for  create & rename event .. 
Check files with specific extension .  
Got this error  for running the process for about 

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/python27/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/opt/python27/lib/python2.7/site-packages/watchdog-0.6.0-py2.7.egg/watchdog/observers/api.py", line 191, in run
    self.queue_events(self.timeout)
  File "/opt/python27/lib/python2.7/site-packages/watchdog-0.6.0-py2.7.egg/watchdog/observers/inotify.py", line 748, in queue_events
    inotify_events = self._inotify.read_events()
  File "/opt/python27/lib/python2.7/site-packages/watchdog-0.6.0-py2.7.egg/watchdog/observers/inotify.py", line 538, in read_events
    wd_path = self._path_for_wd[wd]
KeyError: -1
```

**Comment by ftao** [comment]
My version of watchdog might be too old , i should use the new version .
