### ISSUE TITLE
watchmedo auto-restart is broken on Windows

### ISSUE THREAD

**Issue by vic-trouble** [gorakhargosh/watchdog#387]
>watchmedo auto-restart --patterns="*.py;*.txt" --recursive --command="echo hello" 

Traceback (most recent call last):
  File "C:\Python\Python35\Scripts\watchmedo-script.py", line 9, in <module>
    load_entry_point('watchdog==0.8.3', 'console_scripts', 'watchmedo')()
  File "c:\python\python35\lib\site-packages\watchdog\watchmedo.py", line 566, in main
    parser.dispatch()
  File "c:\python\python35\lib\site-packages\argh\helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "c:\python\python35\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "c:\python\python35\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "c:\python\python35\lib\site-packages\argh\dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "c:\python\python35\lib\site-packages\watchdog\watchmedo.py", line 541, in auto_restart
    handler.start()
  File "c:\python\python35\lib\site-packages\watchdog\tricks\__init__.py", line 147, in start
    self.process = subprocess.Popen(self.command)
  File "c:\python\python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "c:\python\python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

I guess because of the os.setsid usage which is *nix only.

**Comment by dsubak** [comment]
auto-restart seems to exhibit the same behavior on OS X.
