### ISSUE TITLE
consuming events in a recurring loop rather than on occurrence?

### ISSUE THREAD

**Issue by petersilva** [gorakhargosh/watchdog#392]
I find myself not wanting to act on every event as it occurs but instead queue them up for timed processing.   This is also because the first time we try to act on something, it might fail, and we need to retry it later.  Need to track events to retry as well.

Watchdog already has queues and allows for a parent task to be doing other activities, so I created
a 'event_sleep()' to run every sleep seconds.  Demo attached (just a modification of the sample provided in the documentation with event_sleep)  so now the event handlers are just adding events to my own queue.

[w2.txt](https://github.com/gorakhargosh/watchdog/files/690822/w2.txt)   (rename to .py to run)

This works fine (and because of details out of scope, have achieved many-fold speedup as a result.) No problems so far. I copy the new events to a pending list at the beginning of each round of timed processing.  I note that there is potential for events to be missed/dropped if they are added to the new_events list after the copy has occurred, but before it has been emptied.   It is tiny, but it could happen.

I was thinking that it would make more sense not to dispatch the events at all, but instead let them queue up between timed events, and have some sort of api call to take an event from the queue, without any need for any event handler.  Indeed I don't want the events handled, just queued for the periodic processing. That would eliminate the tiny race condition, but I don't see how to do it.

I would imagine something like:
    observer.schedule( None, path, recursive=True)

to say that I wanted nothing to handle events, then issue the start.
then something like like...

   e = observer.consume()
   the would be non-blocking, returning an event from the top of the queue if available
   None otherwise.

Is there an easy way to do something like that?

**Comment by petersilva** [comment]
I have something that works, but it's ugly...
sample code attached (shorter than before!)

[w3.txt](https://github.com/gorakhargosh/watchdog/files/690916/w3.txt)

This code works... but... well watch:


blacklab% python w3.py watch
woke_up! calling event_sleep.
looking...
out of events for now

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/usr/lib/python3/dist-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
AttributeError: 'NoneType' object has no attribute 'dispatch'

woke_up! calling event_sleep.
looking...
consuming <FileModifiedEvent: src_path='watch/bl_sarra.conf'>
looking...
consuming <FileModifiedEvent: src_path='watch/bl_sub.conf'>
looking...
consuming <FileModifiedEvent: src_path='watch/bl_sub_feeder.conf'>
looking...
 ... etc...

so It throws an exception but it works.  If I add the 'dispatch' method, then the queue gets emptied and there is nothing to consume... so I'm stuck with throwing an exception....

**Comment by petersilva** [comment]
Have a patch in my branch... 52d34ba51cc4dbca73cf06613f24a3b84460e95e

https://github.com/petersilva/watchdog

issued a pull request.  dunno about the etiquette... hope this is ok.
