### ISSUE TITLE
_errcheck_bool raise WinError

### ISSUE THREAD

**Issue by Toilal** [gorakhargosh/watchdog#417]
in `observers/winapi.py`

```
def _errcheck_bool(value, func, args):
    if not value:
        raise ctypes.WinError()
    return args
```

Is it valid ? If `value` is `False` or `0`, it will raise exception. Is it the expected behaviour from this function ?

```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "c:\python\python35\Lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Users\FRUP67305\Envs\docker-windows-volume-watcher\lib\site-packages\watchdog\observers\api.py", line 146, in run
    self.queue_events(self.timeout)
  File "D:\Users\FRUP67305\Envs\docker-windows-volume-watcher\lib\site-packages\watchdog\observers\read_directory_changes.py", line 77, in queue_events
    winapi_events = read_events(self._handle, self.watch.is_recursive)
  File "D:\Users\FRUP67305\Envs\docker-windows-volume-watcher\lib\site-packages\watchdog\observers\winapi.py", line 347, in read_events
    buf, nbytes = read_directory_changes(handle, recursive)
  File "D:\Users\FRUP67305\Envs\docker-windows-volume-watcher\lib\site-packages\watchdog\observers\winapi.py", line 307, in read_directory_changes
    raise e
  File "D:\Users\FRUP67305\Envs\docker-windows-volume-watcher\lib\site-packages\watchdog\observers\winapi.py", line 303, in read_directory_changes
    ctypes.byref(nbytes), None, None)
  File "D:\Users\FRUP67305\Envs\docker-windows-volume-watcher\lib\site-packages\watchdog\observers\winapi.py", line 108, in _errcheck_bool
    raise ctypes.WinError()
OSError: [WinError 0] L’opération a réussi.
```

**Comment by Toilal** [comment]
Forget about that :)
