### ISSUE TITLE
Uncatchable OSError raised in Watchdog thread when watched path is deleted

### ISSUE THREAD

**Issue by ghost** [gorakhargosh/watchdog#43]
Start watching a path which already exists, eg.

```
from watchdog import LoggingEventHandler
from watchdog import Observer

event_handler = LoggingEventHandler()
observer = Observer()
observer.schedule(event_handler, path="/path/to/watch")
observer.start()
observer.join()
```

Delete the path being watched ...

> $ rmdir /path/to/watch

Receive uncatchable exception:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.6/site-packages/watchdog-0.5.4-py2.6.egg/watchdog/observers/api.py", line 192, in run
    self.queue_events(self.timeout)
  File "/Library/Python/2.6/site-packages/watchdog-0.5.4-py2.6.egg/watchdog/observers/kqueue.py", line 686, in queue_events
    self.watch.is_recursive)
  File "/Library/Python/2.6/site-packages/watchdog-0.5.4-py2.6.egg/watchdog/utils/dirsnapshot.py", line 227, in __init__
    stat_info = os.stat(self._path)
OSError: [Errno 2] No such file or directory: '/path/to/watch'
```

**Comment by lnxg33k** [comment]
@chwt Hey man, can you please share the code in how you implemented the workaround?

**Comment by rrzaripov** [comment]
@BoboTiG I think this issue can be closed if updated test for #572 will passed?

**Comment by BoboTiG** [comment]
If think so, yes :)
But I cannot see Windows tests, if you can confirm on the PR that it passes, it would be great!

**Comment by rrzaripov** [comment]
@BoboTiG under Windows test passed :-)
