### ISSUE TITLE
KeyError: 'self' in utils/echo.py with v0.8.3 and --trace

### ISSUE THREAD

**Issue by Lucas-C** [gorakhargosh/watchdog#443]
Reproduction steps:
```
# watchmedo log --trace docs/
Traceback (most recent call last):
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/bin/watchmedo", line 11, in <module>
    sys.exit(main())
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/watchdog/watchmedo.py", line 566, in main
    parser.dispatch()
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/watchdog/watchmedo.py", line 334, in log
    ignore_directories=args.ignore_directories)
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/watchdog/utils/echo.py", line 98, in wrapped
    for a in argnames[len(v):] if a not in k]
  File "/home/lucas_cimon/.local/share/virtualenvs/infran_doc/lib/python3.6/site-packages/watchdog/utils/echo.py", line 98, in <listcomp>
    for a in argnames[len(v):] if a not in k]
KeyError: 'self'
```

It doesn't crash without `--trace` specified.

**Comment by Lucas-C** [comment]
This is a duplicate of https://github.com/gorakhargosh/watchdog/issues/381 already resolved
