### ISSUE TITLE
OSError: Permission denied

### ISSUE THREAD

**Issue by SalahAdDin** [gorakhargosh/watchdog#455]
I'm working with `Odoo` in a `docker` container and I decided use all `debug` features; so, I installed `watchdog` and i'm getting this error after that: 
```bash
odoo.web      | Traceback (most recent call last):
odoo.web      |   File "/usr/bin/odoo", line 8, in <module>
odoo.web      |     odoo.cli.main()
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 60, in main
odoo.web      |     o.run(args)
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 175, in run
odoo.web      |     main(args)
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 169, in main
odoo.web      |     rc = odoo.service.server.start(preload=preload, stop=stop)
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 985, in start
odoo.web      |     watcher.start()
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 146, in start
odoo.web      |     self.observer.start()
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/observers/api.py", line 255, in start
odoo.web      |     emitter.start()
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/utils/__init__.py", line 111, in start
odoo.web      |     self.on_thread_start()
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
odoo.web      |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
odoo.web      |     self._inotify = Inotify(path, recursive)
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/observers/inotify_c.py", line 187, in __init__
odoo.web      |     self._add_dir_watch(path, recursive, event_mask)
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/observers/inotify_c.py", line 371, in _add_dir_watch
odoo.web      |     self._add_watch(full_path, mask)
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/observers/inotify_c.py", line 385, in _add_watch
odoo.web      |     Inotify._raise_error()
odoo.web      |   File "/usr/lib/python3/dist-packages/watchdog/observers/inotify_c.py", line 406, in _raise_error
odoo.web      |     raise OSError(os.strerror(err))
odoo.web      | OSError: Permission denied
```

It is related with https://github.com/gorakhargosh/watchdog/issues/75

Why?

**Comment by SalahAdDin** [comment]
I must to revıew thıs because ı don't remember what's the problem.

**Comment by BoboTiG** [comment]
Please reopen with a reproduction code, thanks :)

**Comment by danihodovic** [comment]
Create a file with the root user and the permissions 0700 and this problem can be reproduced. This is common in Docker development environments where a volume is shared by the container and the host.
```
drwx------  19 systemd-coredump root 4.0K Sep 25 20:58 .db
```
