### ISSUE TITLE
Add CI for macOS and Windows

### ISSUE THREAD

**Issue by BoboTiG** [gorakhargosh/watchdog#469]
They are currently not covered and this is *very* bad :)
macOS can be done with Travis-CI. But for Windows, perhaps should wecheck AppVeyor?

**Comment by danilobellini** [comment]
I thought on how to do that. On Travis CI that's possible, but not so easy to keep the compatibility with all Python versions together with the Linux counterparts because Travis doesn't support this OS for the "python" image. Therefore, the CI will be quite slow (it won't have a cached image with Python installed, nor anything alike).

For Windows, a PR bringing AppVeyor is welcome.

**Comment by BoboTiG** [comment]
For Travis and macOS, @blag got it working on that fork: https://github.com/nuxeo/watchdog3. Perhaps could we reuse its work.

**Comment by danilobellini** [comment]
That fork went back and forth with some stuff, it dropped Python 2 compatibility, it had a huge and unrequired style reformatting, it removed of the `watchmedo` script, etc.. I think we should not do here the same that happened there, but probably that fork has some new stuff that's worth backporting here.

"CI" is one of the parts of [almost any library] project that might be really frustrating to deal with. To make it working in all Python versions on Linux, it took way too much time (I had to wait the CI results to know if they were passing, there are some Travis CI "gotchas", etc.), and the several commits in a row in the "ci" branch are now a squashed commit in master (else the git history would be filled of CI trial-and-error commits, and I think that shouldn't happen).

Nevertheless, if you believe you can change the `.travis.yml` to run on macOS without breaking/removing the Linux builds that are running today, go ahead!

**Comment by BoboTiG** [comment]
Of course that fork changed too many things, I was pointing it to highlight the Travis integration that was working on macOS pretty smoothly. And without sacrifying the Linux part.

About the global time it can take to finish, we will save some by dropping several Python versions. In the same spirit, macOS tests can be run only on Python 2.7 and 3.6. Same for Windows.

I will have a look soon for macOS. Feel free to do the Python versions purgation in the meantime :)

**Comment by BoboTiG** [comment]
Some stats :
```shell
pypinfo --percent --pip --markdown watchdog system distro

| system_name | distro_name        | percent | download_count |
| ----------- | ------------------ | ------: | -------------: |
| Linux       | Ubuntu             |  53.22% |        224,713 |
| Linux       | Debian GNU/Linux   |  23.12% |         97,608 |
| Linux       | Alpine Linux       |   6.42% |         27,102 |
| Linux       | Amazon Linux AMI   |   4.11% |         17,370 |
| Windows     | None               |   3.68% |         15,529 |
| Linux       | CentOS Linux       |   3.37% |         14,215 |
| Linux       | None               |   3.28% |         13,850 |
| Darwin      | macOS              |   1.85% |          7,799 |
| Linux       | Kali GNU/Linux     |   0.62% |          2,621 |
| Linux       | Raspbian GNU/Linux |   0.34% |          1,449 |
```
I did not think GNU/Linux was sooooo used.

I will open a PR after the old Python versions drop to have tests on macOS.

**Comment by blag** [comment]
Testing on MacOS is involved, but isn't terribly non-performant, and while having "fast" CI tests is a nice to have, I think it's more important to have _complete_ CI tests. And for a project like this, where it attempts to support all major OSes, I think CI completeness should win over CI performance.

Testing on OS X isn't all that much more complicated:

1. Copy [.travis/install.sh](https://github.com/nuxeo/watchdog3/blob/master/.travis/install.sh) for a script that installs Miniconda. Note that Python 2.7 and 3+ are both supported on OS X.
2. Add `.travis/install.sh` to `.travis.yml` under the `before_install` root key
3. [Add OS X testing environments as usual](https://github.com/nuxeo/watchdog3/pull/19/files#diff-354f30a63fb0907d4ad57269548329e3).

I'm a little too busy at the moment to do anything substantial for this project, but I should be able to answer questions.

And, responding to [this comment](https://github.com/nuxeo/watchdog3/pull/19/files#r205350138), I do have a bunch of unpushed changes that implement integration tests for all backends. The real challenge there is figuring out how each backend handles events differently. I'll see if I can push those (unfinished, but mostly done) changes next week.

**Comment by BoboTiG** [comment]
Thanks @blag, your work is very much appreciated. I already have a patch based on yours to enable CI on macOS, I will open a PR very soon.

**Comment by rrzaripov** [comment]
Working on CI for Windows using appveyor and from time to time fails this test:

```
================================== FAILURES ===================================
_____________________ TestWindowsApiEmitter.test___init__ _____________________
self = <test_watch_observers_winapi.TestWindowsApiEmitter testMethod=test___init__>
    def test___init__(self):
        SLEEP_TIME = 1
        self.emitter.start()
        sleep(SLEEP_TIME)
        mkdir(p('fromdir'))
        sleep(SLEEP_TIME)
        mv(p('fromdir'), p('todir'))
        sleep(SLEEP_TIME)
        self.emitter.stop()
    
        # What we need here for the tests to pass is a collection type
        # that is:
        #   * unordered
        #   * non-unique
        # A multiset! Python's collections.Counter class seems appropriate.
        expected = set([
                       DirCreatedEvent(p('fromdir')),
                       DirMovedEvent(p('fromdir'), p('todir')),
                       ])
        got = set()
    
        while True:
            try:
                event, _ = self.event_queue.get_nowait()
                got.add(event)
            except queue.Empty:
                break
    
        print(got)
>       self.assertEqual(expected, got)
E       AssertionError: Items in the first set but not the second:
E       <DirMovedEvent: src_path='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpg2s6apgg\\fromdir', dest_path='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpg2s6apgg\\todir'>
tests\legacy\test_watch_observers_winapi.py:96: AssertionError
---------------------------- Captured stdout call -----------------------------
{<DirCreatedEvent: src_path='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpg2s6apgg\\fromdir'>}
```

This error occurring with different Python versions. I want to find the cause of problem in near time. After dropping old versions of Python tests running with py27, py34, py35, py36 and py37 (32 and 64-bit).

Second problem is PyPy. For Windows is only 32-bit version of PyPy2 and PyPy3 is aviable, and distributed as zip archive. Steps for download, unpacking, installing pip and tox done well. But when install pip and run tox with PyPy3 something strange happened:

```
RPython traceback:
  File "pypy_interpreter.c", line 42299, in BuiltinCode1_fastcall_1
  File "pypy_module_posix.c", line 4913, in get_terminal_size
Traceback (most recent call last):
  File "C:\projects\watchdog\get-pip.py", line 20651, in <module>
    main()
  File "C:\projects\watchdog\get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "C:\projects\watchdog\get-pip.py", line 175, in bootstrap
    sys.exit(pip._internal.main(args))
  File "C:\Users\appveyor\AppData\Local\Temp\1\tmpebdpnmms\pip.zip\pip\_internal\__init__.py", line 296, in main
  File "C:\Users\appveyor\AppData\Local\Temp\1\tmpebdpnmms\pip.zip\pip\_internal\__init__.py", line 236, in parseopts
  File "C:\Users\appveyor\AppData\Local\Temp\1\tmpebdpnmms\pip.zip\pip\_internal\__init__.py", line 208, in create_main_parser
  File "C:\Users\appveyor\AppData\Local\Temp\1\tmpebdpnmms\pip.zip\pip\_internal\baseparser.py", line 25, in __init__
  File "C:\Users\appveyor\AppData\Local\Temp\1\tmpebdpnmms\pip.zip\pip\_internal\compat.py", line 204, in get_terminal_size
  File "C:\projects\watchdog\pypy3-v6.0.0-win32\lib-python\3\shutil.py", line 1078, in get_terminal_size
    size = os.get_terminal_size(sys.__stdout__.fileno())
SystemError: unexpected internal exception (please report a bug): <WindowsError object at 0x63f5010>; internal traceback was dumped to stderr
Collecting tox
  Downloading https://files.pythonhosted.org/packages/a8/fd/03185994cf64a58a0ea8fe1a824b1e3ab737c2d890a3dc920811f142f52c/tox-3.4.0-py2.py3-none-any.whl (69kB)
Collecting py<2,>=1.4.17 (from tox)
  Downloading https://files.pythonhosted.org/packages/c8/47/d179b80ab1dc1bfd46a0c87e391be47e6c7ef5831a9c138c5c49d1756288/py-1.6.0-py2.py3-none-any.whl (83kB)
Collecting six<2,>=1.0.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pluggy<1,>=0.3.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/f5/f1/5a93c118663896d83f7bcbfb7f657ce1d0c0d617e6b4a443a53abcc658ca/pluggy-0.7.1-py2.py3-none-any.whl
Collecting toml>=0.9.4 (from tox)
  Downloading https://files.pythonhosted.org/packages/c7/19/76c3cb84949a0593767b32b9be83a604d8a68c3580ff5d0ee64856b39ade/toml-0.9.6-py2.py3-none-any.whl
Requirement already satisfied: virtualenv>=1.11.2 in c:\python27\lib\site-packages (from tox) (15.0.1)
Requirement already satisfied: setuptools>=30.0.0 in c:\python27\lib\site-packages (from tox) (39.0.1)
Installing collected packages: py, six, pluggy, toml, tox
Successfully installed pluggy-0.7.1 py-1.6.0 six-1.11.0 toml-0.9.6 tox-3.4.0
GLOB sdist-make: C:\projects\watchdog\setup.py
pypy3 create: C:\projects\watchdog\.tox\pypy3
ERROR: invocation failed (exit code 1), logfile: C:\projects\watchdog\.tox\pypy3\log\pypy3-0.log
ERROR: actionid: pypy3
msg: getenv
cmdargs: "'c:\\python27\\python.exe' -m virtualenv --python 'C:\\projects\\watchdog\\pypy3-v6.0.0-win32\\pypy3.EXE' pypy3"
Using base prefix 'C:\\projects\\watchdog\\pypy3-v6.0.0-win32'
New pypy executable in C:\projects\watchdog\.tox\pypy3\bin\pypy3.EXE
Also creating executable in C:\projects\watchdog\.tox\pypy3\bin\pypy.EXE
Installing setuptools, pip, wheel...
  Complete output from command C:\projects\watchdog\.tox\pypy3\bin\pypy3.EXE - setuptools pip wheel:
  Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/81/17/a6301c14aa0c0dd02938198ce911eba84602c7e927a985bf9015103655d1/setuptools-40.4.1-py2.py3-none-any.whl (569kB)
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.1-py2.py3-none-any.whl\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.1-py2.py3-none-any.whl\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.1-py2.py3-none-any.whl\pip\req\req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.1-py2.py3-none-any.whl\pip\req\req_set.py", line 621, in _prepare_file
    dist = abstract_dist.dist(finder)
  File "c:\python27\lib\site-packages\virtualenv_support\pip-8.1.1-py2.py3-none-any.whl\pip\req\req_set.py", line 108, in dist
    self.req_to_install.source_dir))[0]
IndexError: list index out of range
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\virtualenv.py", line 2316, in <module>
    main()
  File "c:\python27\lib\site-packages\virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "c:\python27\lib\site-packages\virtualenv.py", line 941, in create_environment
    download=download,
  File "c:\python27\lib\site-packages\virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "c:\python27\lib\site-packages\virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\projects\watchdog\.tox\pypy3\bin\pypy3.EXE - setuptools pip wheel failed with error code 2
Running virtualenv with interpreter C:\projects\watchdog\pypy3-v6.0.0-win32\pypy3.EXE
ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('c:\\python27\\python.exe -m virtualenv --python C:\\projects\\watchdog\\pypy3-v6.0.0-win32\\pypy3.EXE pypy3 (see C:\\projects\\watchdog\\.tox\\pypy3\\log\\pypy3-0.log)', 1)
___________________________________ summary ___________________________________
ERROR:   pypy3: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('c:\\python27\\python.exe -m virtualenv --python C:\\projects\\watchdog\\pypy3-v6.0.0-win32\\pypy3.EXE pypy3 (see C:\\projects\\watchdog\\.tox\\pypy3\\log\\pypy3-0.log)', 1)
Command exited with code 1
```

PyPy2 installing currently into watchdog source directory, and when pytest runs it found all tests in directory (and also PyPy2 tests), but this can be resolved adding tests/ directory into tox.ini pytest addopts.

**Comment by BoboTiG** [comment]
I would say for Windows (as I have done with macOS), just test on Python 2.7 and either 3.7.
