### ISSUE TITLE
How to handle Exceptions in a watchdog thread

### ISSUE THREAD

**Issue by acastr** [gorakhargosh/watchdog#481]
I'm watching a directory on a Windows share. Whenever a connection is lost, the watchdog observer thread throws an exception.
How and where in the code do you properly handle this exception?
This is a traceback when I disconnect a mapped network drive:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Share\Python_projects\MorpheusPlaylistConvertor\venv\lib\site-packages\watchdog\observers\api.py", line 146, in run
    self.queue_events(self.timeout)
  File "D:\Share\Python_projects\MorpheusPlaylistConvertor\venv\lib\site-packages\watchdog\observers\read_directory_changes.py", line 75, in queue_events
    winapi_events = read_events(self._handle, self.watch.is_recursive)
  File "D:\Share\Python_projects\MorpheusPlaylistConvertor\venv\lib\site-packages\watchdog\observers\winapi.py", line 346, in read_events
    buf, nbytes = read_directory_changes(handle, recursive)
  File "D:\Share\Python_projects\MorpheusPlaylistConvertor\venv\lib\site-packages\watchdog\observers\winapi.py", line 306, in read_directory_changes
    raise e
  File "D:\Share\Python_projects\MorpheusPlaylistConvertor\venv\lib\site-packages\watchdog\observers\winapi.py", line 302, in read_directory_changes
    ctypes.byref(nbytes), None, None)
  File "D:\Share\Python_projects\MorpheusPlaylistConvertor\venv\lib\site-packages\watchdog\observers\winapi.py", line 107, in _errcheck_bool
    raise ctypes.WinError()
OSError: [WinError 59] An unexpected network error occurred.

**Comment by gewenpulan** [comment]
do you solve this?

**Comment by acastr** [comment]
Sorry, I never found a perfect solution without completely changing the watchdog code.
