### ISSUE TITLE
watchmedo chokes upon encountering sockets

### ISSUE THREAD

**Issue by UnitedMarsupials** [gorakhargosh/watchdog#509]
Trying to learn, how to use watchdog -- to be able to write scripts portable between BSD and Linux. Got the below error on FreeBSD:
```
% watchmedo log /tmp/
Traceback (most recent call last):
  File "/opt/bin/watchmedo", line 11, in <module>
    load_entry_point('watchdog==0.9.0', 'console_scripts', 'watchmedo')()
  File "/opt/lib/python3.6/site-packages/watchdog/watchmedo.py", line 573, in main
    parser.dispatch()
  File "/opt/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/opt/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/lib/python3.6/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/opt/lib/python3.6/site-packages/watchdog/watchmedo.py", line 354, in log
    observe_with(observer, handler, args.directories, args.recursive)
  File "/opt/lib/python3.6/site-packages/watchdog/watchmedo.py", line 118, in observe_with
    observer.schedule(event_handler, pathname, recursive)
  File "/opt/lib/python3.6/site-packages/watchdog/observers/api.py", line 290, in schedule
    timeout=self.timeout)
  File "/opt/lib/python3.6/site-packages/watchdog/observers/kqueue.py", line 461, in __init__
    walker_callback)
  File "/opt/lib/python3.6/site-packages/watchdog/utils/dirsnapshot.py", line 239, in __init__
    walker_callback(p, st)
  File "/opt/lib/python3.6/site-packages/watchdog/observers/kqueue.py", line 457, in walker_callback
    self._register_kevent(path, stat.S_ISDIR(stat_info.st_mode))
  File "/opt/lib/python3.6/site-packages/watchdog/observers/kqueue.py", line 475, in _register_kevent
    self._descriptors.add(path, is_directory)
  File "/opt/lib/python3.6/site-packages/watchdog/observers/kqueue.py", line 260, in add
    self._add_descriptor(KeventDescriptor(path, is_directory))
  File "/opt/lib/python3.6/site-packages/watchdog/observers/kqueue.py", line 345, in __init__
    self._fd = os.open(path, WATCHDOG_OS_OPEN_FLAGS)
OSError: [Errno 45] Operation not supported: '/tmp/dbus-S0hRqBusTm'
% ls -l /tmp/dbus-S0hRqBusTm
srwxrwxrwx  1 mi  wheel  0 Jan 14 10:02 /tmp/dbus-S0hRqBusTm
```

**Comment by rrzaripov** [comment]
@UnitedMarsupials thank you for bug report!
