### ISSUE TITLE
Hacking docs result in unhandled exceptions

### ISSUE THREAD

**Issue by exarkun** [gorakhargosh/watchdog#517]
`docs/source/hacking.rst` says to run `python tools/bootstrap.py --distribute` to set up a development environment.  This fails:

```
$ python tools/bootstrap.py --distribute
Traceback (most recent call last):
  File "tools/bootstrap.py", line 179, in <module>
    options.setup_source).read().replace('\r\n'.encode(), '\n'.encode())
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by rrzaripov** [comment]
@exarkun I think bootstrap.py little bit outdated, and need to be updated. Possible creation of development environment may rely on modern tools like virtualenv, pip or something another. And yes, documentation also need to be updated.

**Comment by BoboTiG** [comment]
@rrzaripov is right, I am closing the issue.
