### ISSUE TITLE
KeyError in `Inotify.read_events` when adding multiple items to watched folder

### ISSUE THREAD

**Issue by SamSchott** [gorakhargosh/watchdog#600]
A `KeyError` occurs occasionally when adding multiple items to the watched folder at once. This happens while cleaning up ignored events from `_wd_for_path`:

```python
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/miniconda3/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 60, in run
    inotify_events = self._inotify.read_events()
  File "/opt/miniconda3/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 340, in read_events
    if self._wd_for_path[path] == wd:
KeyError: b'/home/ss2151/Dropbox (Maestral)/untitled folder'
```

**Comment by SamSchott** [comment]
Issue seems to be resolved in the new release.
