### ISSUE TITLE
FSEvents: Cannot watch the same path with two different observers

### ISSUE THREAD

**Issue by kreichgauer** [gorakhargosh/watchdog#63]
When you schedule a watch on the same path with two different observers, the fsevents C extension runs into an error. This is because `_watchdog_fsevents` is a singleton and `watchdog_fsevents_add_watch` returns `null` if a watch has already been scheduled.

Test case:

``` python
>>> from watchdog.observers import Observer
>>> from watchdog.events import LoggingEventHandler
>>> obs = Observer()
>>> other_obs = Observer()
>>> handler = LoggingEventHandler()
>>> other_handler = LoggingEventHandler()
>>> path = '/tmp'
>>> obs.schedule(handler, path)
<ObservedWatch: path=/tmp, is_recursive=False>
>>> other_obs.schedule(other_handler, path)
<ObservedWatch: path=/tmp, is_recursive=False>
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "[...]/watchdog/src/watchdog/observers/fsevents.py", line 140, in run
    self.pathnames)
SystemError: error return without exception set

>>> 
```

**Comment by jamesabel** [comment]
I have what seems to be a similar problem.

Code:
```

import os
import time

from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler


class FileModifiedHandler(FileSystemEventHandler):

    def __init__(self, path):
        self.observer = Observer()
        self.observer.schedule(self, path, recursive=True)
        self.observer.start()

    def on_modified(self, event):
        print(event)

    def stop(self):
        self.observer.stop()
        self.observer.join()


def main(n):
    path = '.'
    fhs = [FileModifiedHandler(path) for _ in range(0, n)]
    time.sleep(2)
    with open(os.path.join(path, 'temp.txt'), 'w') as f:
        f.write('hi')
    time.sleep(2)
    [fh.stop() for fh in fhs]


if __name__ == '__main__':
    print('this works:')
    main(1)  # OK
    print('this fails:')
    main(2)  # fails
```
Output:

```
this works:
<FileModifiedEvent: src_path='./temp.txt'>
this fails:
<FileModifiedEvent: src_path='./temp.txt'>
2016-05-31 19:03 Python[63998] (FSEvents.framework) FSEventStreamStop(): failed assertion 'streamRef != NULL'

2016-05-31 19:03 Python[63998] (FSEvents.framework) FSEventStreamInvalidate(): failed assertion 'streamRef != NULL'

2016-05-31 19:03 Python[63998] (FSEvents.framework) FSEventStreamRelease(): failed assertion 'streamRef != NULL'

Traceback (most recent call last):
  File "/Users/james/projects/experiments/watchdog_experiment/watchdog_experiment.py", line 38, in <module>
    main(2)  # fails
  File "/Users/james/projects/experiments/watchdog_experiment/watchdog_experiment.py", line 31, in main
    [fh.stop() for fh in fhs]
  File "/Users/james/projects/experiments/watchdog_experiment/watchdog_experiment.py", line 31, in <listcomp>
    [fh.stop() for fh in fhs]
  File "/Users/james/projects/experiments/watchdog_experiment/watchdog_experiment.py", line 20, in stop
    self.observer.stop()
  File "/Users/james/projects/experiments/watchdog_experiment/venv/lib/python3.4/site-packages/watchdog/utils/__init__.py", line 99, in stop
    self.on_thread_stop()
  File "/Users/james/projects/experiments/watchdog_experiment/venv/lib/python3.4/site-packages/watchdog/observers/api.py", line 357, in on_thread_stop
    self.unschedule_all()
  File "/Users/james/projects/experiments/watchdog_experiment/venv/lib/python3.4/site-packages/watchdog/observers/api.py", line 353, in unschedule_all
    self._clear_emitters()
  File "/Users/james/projects/experiments/watchdog_experiment/venv/lib/python3.4/site-packages/watchdog/observers/api.py", line 230, in _clear_emitters
    for emitter in self._emitters:
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

Process finished with exit code 1
```

**Comment by BoboTiG** [comment]
Fixed sometime ago, added a test to ensure no regression in f3c7f84.
