### ISSUE TITLE
Windows 10 'watchdog' is not a package

### ISSUE THREAD

**Issue by plegault3397** [gorakhargosh/watchdog#646]
```bash
pip install watchdog --force
Collecting watchdog
  Using cached watchdog-0.10.2.tar.gz (95 kB)
Collecting pathtools>=0.1.1
  Using cached pathtools-0.1.2.tar.gz (11 kB)
Installing collected packages: pathtools, watchdog
  Attempting uninstall: pathtools
    Found existing installation: pathtools 0.1.2
    Uninstalling pathtools-0.1.2:
      Successfully uninstalled pathtools-0.1.2
    Running setup.py install for pathtools ... done
  Attempting uninstall: watchdog
    Found existing installation: watchdog 0.10.2
    Uninstalling watchdog-0.10.2:
      Successfully uninstalled watchdog-0.10.2
    Running setup.py install for watchdog ... done
Successfully installed pathtools-0.1.2 watchdog-0.10.2
```

```python
import sys
import time
import logging
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
    path = sys.argv[1] if len(sys.argv) > 1 else '.'
    event_handler = LoggingEventHandler()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
```

```bash
Traceback (most recent call last):
  File "watchdog.py", line 4, in <module>
    from watchdog.observers import Observer
  File "watchdog.py", line 4, in <module>
    from watchdog.observers import Observer
ModuleNotFoundError: No module named 'watchdog.observers'; 'watchdog' is not a package
```

**Comment by BoboTiG** [comment]
If you are using `python -m pip ...` instead of `pip ...` (to be sure this is the same Python executable used with both the installation and script run), what ar ethe results?

**Comment by BoboTiG** [comment]
Oh, I get it: rename your script from `watchdog.py` to another name that is not conflicting with `watchdog.`

**Comment by plegault3397** [comment]
Lol

Thanks that did it
