### ISSUE TITLE
[0.10.2] Build test fails on Linux

### ISSUE THREAD

**Issue by tuxmaster5000** [gorakhargosh/watchdog#657]
It looks like that Windows tests are not skipped correctly:
```
+ /usr/bin/python3 setup.py test
running test
running egg_info
writing src/watchdog.egg-info/PKG-INFO
writing dependency_links to src/watchdog.egg-info/dependency_links.txt
writing entry points to src/watchdog.egg-info/entry_points.txt
writing requirements to src/watchdog.egg-info/requires.txt
writing top-level names to src/watchdog.egg-info/top_level.txt
reading manifest file 'src/watchdog.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.h' under directory 'src'
writing manifest file 'src/watchdog.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    zip_safe=False
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 229, in run
    self.run_tests()
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 251, in run_tests
    exit=False,
  File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib64/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/watchdog-0.10.2/tests/test_observers_winapi.py", line 23, in <module>
    pytest.skip("Windows only.", allow_module_level=True)
  File "/usr/lib/python3.6/site-packages/_pytest/outcomes.py", line 145, in skip
    raise Skipped(msg=msg, allow_module_level=allow_module_level)
Skipped: Windows only.
```

**Comment by kravietz** [comment]
I'm getting - looks like Windows compiler flags are mistakenly added on Linux ` /DUNICODE /W4`:
```
# pip3 install watcher
Collecting watcher
  Downloading watcher-0.2.1.zip (13 kB)
Building wheels for collected packages: watcher
  Building wheel for watcher (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g1u56k6q/watcher/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g1u56k6q/watcher/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d
/tmp/pip-wheel-wbr_w9ir
       cwd: /tmp/pip-install-g1u56k6q/watcher/
  Complete output (21 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  copying FileSystemWatcher.py -> build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/watcher
  copying watcher/__init__.py -> build/lib.linux-x86_64-3.7/watcher
  creating build/lib.linux-x86_64-3.7/watcher/tests
  copying watcher/tests/test_FileSystemWatcher.py -> build/lib.linux-x86_64-3.7/watcher/tests
  copying watcher/tests/__init__.py -> build/lib.linux-x86_64-3.7/watcher/tests
  copying watcher/tests/test_watcher.py -> build/lib.linux-x86_64-3.7/watcher/tests
  copying watcher/tests/__main__.py -> build/lib.linux-x86_64-3.7/watcher/tests
  running build_ext
  building 'watcher._watcher' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c src/_watcher.c -o build/temp.linux-x86_64-3.7/src/_watcher.o /W4 /DUNICODE
  x86_64-linux-gnu-gcc: error: /W4: No such file or directory
  x86_64-linux-gnu-gcc: error: /DUNICODE: No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for watcher
  Running setup.py clean for watcher
Failed to build watcher
```

**Comment by BoboTiG** [comment]
It is not the recommended way to run tests. You should use `tox`, or event `pytest` directly.

There is that warning since a while when you run `python setup.py tests`:
> WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.

**Comment by BoboTiG** [comment]
@kravietz this is the `watchdog` repository, not `watcher` ;)
You will likely have better luck reporting the issue in their repository instead.
