### ISSUE TITLE
Could not import 'DirectorySnapshot' from watchdog.observers.fsevents

### ISSUE THREAD

**Issue by OrangeFran** [gorakhargosh/watchdog#708]
Here's the output:

```
Traceback (most recent call last):
  File "/usr/local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/maestral/cli.py", line 223, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/maestral/cli.py", line 578, in start
    from maestral.main import Maestral
  File "/usr/local/lib/python3.8/site-packages/maestral/main.py", line 39, in <module>
    from maestral.sync import SyncMonitor, SyncDirection
  File "/usr/local/lib/python3.8/site-packages/maestral/sync.py", line 81, in <module>
    from maestral.fsevents import Observer
  File "/usr/local/lib/python3.8/site-packages/maestral/fsevents/__init__.py", line 13, in <module>
    from .fsevents import OrderedFSEventsObserver as Observer
  File "/usr/local/lib/python3.8/site-packages/maestral/fsevents/fsevents.py", line 19, in <module>
    from watchdog.observers.fsevents import (  # type: ignore
ImportError: cannot import name 'DirectorySnapshot' from 'watchdog.observers.fsevents' (/usr/local/lib/python3.8/site-packages/watchdog/observers/fsevents.py)
```

It's probably just something simple or some dependency fail by me.
I used python3.8.6 and python3.9 and both failed here. Running this on MacOS Catalina 10.15.7.

Edit: Wrong repo, sorry

**Comment by BoboTiG** [comment]
You can import from https://github.com/gorakhargosh/watchdog/blob/a5cc00dc57957e2ea10e94dbdec05973993a737b/src/watchdog/utils/dirsnapshot.py#L61
