### ISSUE TITLE
pypi install of 1.0.2 does not install argh 

### ISSUE THREAD

**Issue by wasade** [gorakhargosh/watchdog#743]
Please see below. I'd be happy to submit a pull request for a modification to `setup.py` if that would be of help

```bash
$ pip --version
pip 20.1.1 from /home/normal/miniconda3/envs/example/lib/python3.6/site-packages/pip (python 3.6)
$ pip install watchdog
Collecting watchdog
  Downloading watchdog-1.0.2-py3-none-manylinux2014_x86_64.whl (72 kB)
     |████████████████████████████████| 72 kB 363 kB/s 
Installing collected packages: watchdog
Successfully installed watchdog-1.0.2
$ watchmedo
Traceback (most recent call last):
  File "/home/normal/miniconda3/envs/example/bin/watchmedo", line 5, in <module>
    from watchdog.watchmedo import main
  File "/home/normal/miniconda3/envs/example/lib/python3.6/site-packages/watchdog/watchmedo.py", line 34, in <module>
    from argh import arg, aliases, ArghParser, expects_obj
ModuleNotFoundError: No module named 'argh'
$ pip install argh
Collecting argh
  Downloading argh-0.26.2-py2.py3-none-any.whl (30 kB)
Installing collected packages: argh
Successfully installed argh-0.26.2
$ watchmedo
usage: watchmedo [-h] [--version]
                 {tricks-from,tricks,tricks-generate-yaml,generate-tricks-yaml,log,shell-command,auto-restart}
                 ...
```

**Comment by di** [comment]
I think you want to install the `watchmedo` extra with `pip install watchdog[watchmedo]`.

**Comment by wasade** [comment]
Ah, I see that now. Sorry for the oversight, and thank you for the rapid
response!
