### ISSUE TITLE
Missing package after installing watchdog 'ModuleNotFoundError: No module named 'argh''

### ISSUE THREAD

**Issue by mikeysan** [gorakhargosh/watchdog#755]
I installed watchdog using `pip3 install watchdog`.

#### The problem
When I ran `watchmedo --help` I got a message saying 'argh' was missing.

#### System infor
Linux Mint 20.01

#### Console output
```sh
sspade@Honeypot-001:~$ pip3 install watchdog
Collecting watchdog
  Downloading watchdog-1.0.2-py3-none-manylinux2014_x86_64.whl (72 kB)
     |████████████████████████████████| 72 kB 969 kB/s 
Installing collected packages: watchdog
Successfully installed watchdog-1.0.2
sspade@Honeypot-001:~$ watchmedo --help
Traceback (most recent call last):
  File "/home/sspade/.local/bin/watchmedo", line 5, in <module>
    from watchdog.watchmedo import main
  File "/home/sspade/.local/lib/python3.8/site-packages/watchdog/watchmedo.py", line 34, in <module>
    from argh import arg, aliases, ArghParser, expects_obj
ModuleNotFoundError: No module named 'argh'
sspade@Honeypot-001:~$ pip3 install -U watchdog[watchmedo]
Requirement already up-to-date: watchdog[watchmedo] in ./.local/lib/python3.8/site-packages (1.0.2)
Collecting argh>=0.24.1; extra == "watchmedo"
  Downloading argh-0.26.2-py2.py3-none-any.whl (30 kB)
Requirement already satisfied, skipping upgrade: PyYAML>=3.10; extra == "watchmedo" in /usr/lib/python3/dist-packages (from watchdog[watchmedo]) (5.3.1)
Installing collected packages: argh
Successfully installed argh-0.26.2
```

#### Workaround
Installing watchmedo seems to resolve the issue, but I think it should be looked into.
`pip3 install -U watchdog[watchmedo]`

**Comment by BoboTiG** [comment]
You did find the right command to type to solve the issue :)
