### ISSUE TITLE
Running watchmedo fails with ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by w7089** [gorakhargosh/watchdog#826]
I installed `watchdog==2.1.3` using `pip3 install -r requirements.txt`.

Then ran `watchmedo shell-command  --patterns="*.py" --command='python3 export_jira_metrics.py'  .`

First, it failed with:
```

Traceback (most recent call last):
  File "/usr/local/bin/watchmedo", line 5, in <module>
    from watchdog.watchmedo import main
  File "/usr/local/lib/python3.9/site-packages/watchdog/watchmedo.py", line 29, in <module>
    import yaml
```

I installed `pyyaml==5.4.1`, then the same command failed with

```
Traceback (most recent call last):
  File "/usr/local/bin/watchmedo", line 5, in <module>
    from watchdog.watchmedo import main
  File "/usr/local/lib/python3.9/site-packages/watchdog/watchmedo.py", line 34, in <module>
    from argh import arg, aliases, ArghParser, expects_obj
ModuleNotFoundError: No module named 'argh'
```

I installed `argh==0.26.2` and the command succeeded. 

Is the issue related to the fact that there's neither `pyyaml`, nor `argh` in `setup.py` of `watchdog`?

**Comment by BoboTiG** [comment]
Have a look at https://github.com/gorakhargosh/watchdog#installation:
> or to install the watchmedo utility:
> $ python -m pip install -U "watchdog[watchmedo]"
